site_name: The BackBee documentation
site_url: http://www.backbee.com/
site_description: The BackBee documentation

repo_url: https://github.com/backbee/docs

docs_dir: doc
theme: 'bootstrap'

pages:
- Introduction: 'index.md'
- User documentation:
    - 'Installation of BackBee CMS': 'user-documentation/installation.md'

copyright: Copyright &copy; 2014-2015, <a href="http://www.backbee.com">BackBee project</a>.
