site_name: BackBee documentation
site_url: http://www.backbee.com/
site_description: The BackBee documentation

repo_url: https://github.com/backbee/docs

docs_dir: doc
theme: 'bootstrap'

pages:
- ['index.md', 'Summary']
- ['introduction.md', 'Introduction', 'Introduction']

copyright: Copyright &copy; 2014-2015, <a href="http://www.backbee.com">BackBee project</a>.
